services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - "${PWD}/WebAPILaborService:/var/www/html"
      - ./storage/app/public:/var/www/public/storage
    networks:
      - mynet
    depends_on:
      - laravel-db

  laravel-db:
    image: postgres:15
    container_name: laravel-db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8081:80"   # можно заменить на 80, если свободно
    volumes:
      - "${PWD}/WebAPILaborService:/var/www/html"
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - mynet

networks:
  mynet:


volumes:
  pgdata:
