services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=laravel-db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8081
    networks:
      - tetrakomnet
    depends_on:
      - laravel-db

  laravel-db:
    image: postgres:17-alpine
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tetrakomnet

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./storage/app/public:/var/www/html/public/storage
    depends_on:
      - laravel-app
    networks:
      - tetrakomnet

networks:
  laravel-network:
    external: true

volumes:
  postgres_data:
